import Head from "next/head";
import Layout from "../components/layout";
import styles from "../styles/Home.module.scss";

import WevDev from "../components/webdev-logo/webdev.svg"

export default function Home() {
  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>bananabrann - Home</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div>

          b
          a
          n
          a
          n
          a
        </div>

      </div>
    </Layout>
  );
}
