name: "Rebuild website"

on:
  schedule:
  - cron: "0 */8 * * *"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: "ubuntu-latest"
    steps:
    - name: "Call Vercel build webhook"
      uses: wei/curl@master
      with:
        args: ${{ secrets.VERCEL_DEPLOY_URL }}
